In [ ]:
# 01_tensor_basics.ipynb
# Tensor creation, operations, and shape/dtype inspection

import torch

# Create random tensor with normal distribution
data = torch.randn(2, 3)
print(data)
print(data + 5)
print(data + data)
print(data.shape)
print(data.dtype)

# Zero tensor
data = torch.zeros([2, 4])
print(data)

# Ones tensor
data = torch.ones([2, 4])
print(data)

# Identity matrix
data = torch.eye(4)
print(data)

# List vs tensor operations
lst1 = [1, 2]
lst2 = [3, 4]
tor1 = torch.tensor([1, 2])
tor2 = torch.tensor([3, 4])

print(lst1 + lst2)      # List concatenation
print(tor1 + tor2)      # Tensor element-wise addition
print(sum(tor1 + tor2)) # Sum of elements
print(tor1.dot(tor2))   # Dot product
print(torch.dot(tor1, tor2))
print(torch.matmul(tor1, tor2))
print(torch.matmul(tor1.view(1, -1), tor2)[0])

# Matrix multiplication
mat1 = torch.tensor([[2, 5, 8], [5, 3, 1]])
mat2 = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(mat1)
print(mat2)
print(mat1.shape, mat2.shape)
print(torch.matmul(mat1, mat2))
print(torch.matmul(mat2, mat1))

# Tensor statistics
data = torch.randn(4, 3)
print(data)
print(data[2, :])     # Row vector
print(data[:1])       # Column vector (first row)
print(data[2][1])     # Single element

print(torch.sum(data))
print(torch.mean(data))
print(torch.var(data))
print(torch.std(data))

print(torch.sum(data, dim=0)) # Sum by column
print(torch.sum(data, dim=1)) # Sum by row
print(torch.sum(data).item()) # Extract scalar value

# Conditional operation with torch.where
print(torch.where(data > 0, torch.ones(data.shape), torch.zeros(data.shape)))

# NumPy conversion
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
a = torch.from_numpy(b)
print(a)

tensor([[ 0.9580, -1.9045,  1.1201],
        [ 0.6370,  0.7848, -0.6711]])
tensor([[5.9580, 3.0955, 6.1201],
        [5.6370, 5.7848, 4.3289]])
tensor([[ 1.9160, -3.8091,  2.2403],
        [ 1.2740,  1.5695, -1.3421]])
torch.Size([2, 3])
torch.float32
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
[1, 2, 3, 4]
tensor([4, 6])
tensor(10)
tensor(11)
tensor(11)
tensor(11)
tensor(11)
tensor([[2, 5, 8],
        [5, 3, 1]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([2, 3]) torch.Size([3, 2])
tensor([[57, 72],
        [19, 28]])
tensor([[12, 11, 10],
        [26, 27, 28],
        [40, 43, 46]])
tensor([[ 1.1378, -2.5274, -0.8405],
        [-0.1514,  0.4240,  0.7569],
        [-0.0201,  0.2930,  0.8302],
        [ 0.3093,  0.7691, -1.5043]])
tensor([-0.0201,  0.2930,  0.8302])
tensor([[ 1.1378, -2.5274, -0.8405]])
t